### ISSUE TITLE
Rename classes directory

### ISSUE THREAD

**Issue by altrisi** [replaceitem/carpet-discarpet#1]
Classes directory isn't being uploaded to GitHub, probably because classes is .gitignored for gradle.
Therefore, trying to build Discarpet from the code in the repo results in an error.

Solutions:
-Rename classes directory to any other thing (and all of it's references)
-Remove classes from gitignore and hope Gradle won't start uploading random files (which it probably will, at some point)

**Comment by replaceitem** [comment]
Thank you for pointing that out! i moved it out of the directory (which has a silly name since those are all classes lol)
https://github.com/replaceitem/carpet-discarpet/commit/75ae46fedc6dde55eb793f68aef8ab56374f84bb
