### ISSUE TITLE
Searching a way to detect if somebody removes a reaction

### ISSUE THREAD

**Issue by Isax03** [replaceitem/carpet-discarpet#10]
Is there a way to see/detect if sombody has removed a reaction?
For example: `__on_discord_reaction(reaction,user)` detects if there is a reaction and does an action, but if I want to do the opposite action _(remove an element from a list/dictionary, set a boolean to false, or something else)_ when the reaction is removed, I can't do it

**Comment by replaceitem** [comment]
Yeah thats kinda missing
Fixed with 488ef5a33853b5d01627e9b2d49ccbb9f8e3f483

**Comment by replaceitem** [comment]
I just updated the 1.4.21 release to include that
