### ISSUE TITLE
Discarpet sending unwanted messages.

### ISSUE THREAD

**Issue by GamesaltGames** [replaceitem/carpet-discarpet#17]
![image](https://user-images.githubusercontent.com/69097548/121277615-9b3c4500-c896-11eb-8b97-640a3bf09762.png)
The code I'm using is the example code for Minecraft to Discord chat (as well as the other way around). I believe this is an issue with my server hosting but I am not getting any messages in console when it is happening, I am using Shockbyte for hosting. If there is a way to filter messages only from the user that would work perfectly for what I am doing.

**Comment by GamesaltGames** [comment]
I was able to fix the issue by changing from sending the text of the message, to the type so I could get that, then I removed that type from being sent.

**Comment by replaceitem** [comment]
Alright good, yeah the `type` is exactly for that purpose 👍
