### ISSUE TITLE
Role Support

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#18]
First and foremost, wonderful extension to scarpet. Thank you for providing this. I really appreciate the flexibility this allows me in bridging my Discord server with my Minecraft server. In combination with your HTTP function in [scarpet-additions
](https://github.com/replaceitem/scarpet-additions) I can mimic DiscordSRV to a decently high degree. Overall I am very satisfied with what you've provided.

I'm writing this to request a new feature that would immensely improve my bot setup. Would it be possible to include Discord roles?

Right now I have to handle roles with a separate Discord bot, then send messages to the Discarpet bot through a private text channel as if it were a named pipe. Unfortunately it is a one way pipe, so the Discarpet bot is unable to talk back to the Discord bot. This could be solved if I host the Discord bot myself and modify it to not ignore other bots, but that is significant work for me. Either way, using a private Discord channel as a named pipe for IPC is not ideal.

I understand that this is opening a can of worms, as the more features you support the more there is to wire together. Roles touch a bit of everything too.

The `dc_role` type could have: _(loosely based on dc_user)_
- `id` (String)
- `name` (String)
- `mention_tag` (String)
- `color` (number)

I propose something along the lines of:
- `dc_role_from_id(id)` => returns role (dc_role).
- `dc_add_roles(user, role1, role2, ...)` => add role(s) to the user, returning roles added.
- `dc_remove_roles(user, role1, role2, ...)` => remove role(s) from the user, returning roles removed.

`dc_server` would also gain `roles`, a List of all roles on the server.
`dc_user` would also gain `roles`, a List of all roles the user has.
Alternatively, there could be functions instead to avoid needless API calls for each `dc_user` and `dc_server` constructed:
- `dc_get_user_roles(user, amount?)` Where `amount` is how many roles to get, by default `null` meaning all roles.
- `dc_get_server_roles(server)`

I'd prefer functions, to obtain up to date info when desired. Regardless of the solution implemented, I believe a returned List of roles ought to be sorted by role hierarchy highest to lowest.
I could see helper functions being made available to mitigate needless API calls, such as ones that iterate until a role with color is found, returning it, `dc_get_user_color_role(user)`.
This area has a lot to consider and explore, if only to mitigate API calls and provide a thorough interface to the user. There are very few cases where you actually want _all_ of the user's roles.

I believe that covers everything necessary for a minimal implementation. Though I am likely forgetting something.

I hope this helps, even if just a little. Thanks for considering my request! I'd add it myself, but Java is a foreign land to me still, let alone Fabric mods and extending Scarpet. Though this might motivate me to learn if necessary haha!

**Comment by replaceitem** [comment]
This all sounds very good, all the functions you provided make perfect sense i think, and will help me implement this. I will add this as soon as possoble.

**Comment by GunnyWaffle** [comment]
ah! Thank you so much! I'm so glad that what I provided is of help. :D 

There is one addition that I'd like to make, as it would result in rather powerful capabilities. It came to me just now.
As my proposal stands, you can only interact with the roles of a user within the scope of a Discarpet event that provides a `dc_user` value (directly or indirectly). It would be potent to add `dc_user_from_id(id)`, enabling a broader API.

An example that comes to mind is a slash command that allows Discord users to bind their Minecraft account to their Discord account. With a map of Minecraft uuid to Discord user id, one could get the `dc_user` of a player at any point in time.

This could allow things such as:
- adding/giving roles outside the scope of Discarpet events.
- @-ing the player on Discord.
- giving Discord mods the Discord handle of a user for moderation purposes.
- earning Discord roles for performing feats in Minecraft.
- granting an OP role to OP'd players.
- assigning a team role.
- and many more. My imagination is running a bit wild with this one.

I feel there are endless possibilities to letting one interact with users outside the context of Discarpet events that provide them. It may even be helpful to provide account binding as a first class citizen of this mod. Though, that is not necessary to achieve these features and would simply be a helper for the scarpet developer.

Let me know if this should be it's own issue. It is only marginally related to this one. Such that it marries well with roles, but is not limited to the implementation of roles.

Thanks again, I can't wait to see roles added!

**Comment by replaceitem** [comment]
I totally thought getting a user by id was already a thing. But it's not. The problem with that is, not all users are cached by discarpet, meaning if it's not cached, getting the user will require it to be requested from the discord api, which takes a while. So the `dc_user_from_id` function wouldn't return the user directly. Instead, you would need to pass a callback function that gets executes with the user when it's ready (Just like with `http()` in scarpet additions):

```
dc_user_from_id(id, _(user) -> (

);
```

This is a problem i had in many situations in discarpet, and a callback function seems too messy...
Maybe i will implement such functions with a new return value type that wraps a CompletableFuture in java (maybe you know about Promises in JavaScript, its a similar thing), since thats what discarpet uses for returning values from api calls.

```
future = dc_user_from_id(id);

//wait for the future to return the user
//this would block the script untill the user is ready
user = future_join(future);

//or assign a callback
//this would proceed the script immediately, and run the callback when ready
future_then(future, _(user) -> (...));
```

I would prefer the 2nd option, since it allows for two ways of handling such return values.

This is just an idea i had for a cleaner solution to this problem. Doesn't really relate to this issue, but some feedback on it would help.

**Comment by GunnyWaffle** [comment]
Yeah that makes a lot of sense. When there is a Discord API call involved, especially non-trivial, it should not block on the calling thread.

`dc_user_from_id(id)` would hide the act of blocking. Developers would unknowingly call a blocking function on the main thread.  Leaving that to documentation is misleading.

A future would solve this, so would the callback. I can see both being of use. Though would it be possible to use a scarpet `task` instead? Or to wrap your future in a `task`? That would keep Discarpet in line with the threading model of scarpet and give maximum flexibility.

In an ideal world developers would get to choose. I propose:
````
// callback, for simple main thread use cases
dc_user_from_id(id, _(user) -> (
    // use the dc_user value
));

// task, for advanced thread handling
user_task = dc_user_from_id_task(id, executor?);

// now the developer may handle this how they wish
user = task_value(user_task);  // helpful if you choose to cache users, to check if cache was hit
user = task_join(user_task);  // simple if dc_user_from_id_task was called in its own thread already
task(__handle_user_task, user_task);  // similar to your future_then, but gives the developer a task to monitor
synchronize('users', global_user_tasks += user_task);  // pool processing of tasks on another thread
````

**Comment by replaceitem** [comment]
Oh yeah that makes sense, extending the `ThreadValue`. `task_join` already exists, so adding something like `task_then` to attach a function to run when the task is complete would make sense.

```
//blocking main thread
user = task_join(dc_user_from_id(id));

//attach callback (non blocking)
task_then(dc_user_from_id(id), _(user)->(
   
));
```

**Comment by replaceitem** [comment]
Though i don't think its neccesary to include a executor, it just adds extra complexity to a lot of functions

**Comment by replaceitem** [comment]
It seems like extending the ThreadValue isn't possible, since the ThreadValue constructor expects a scarpet function, which isn't the case here. But if we don't extend the value type, the scarpet `task_*` functions work work on them anymore.
So it seems like we need custom functions, which is a shame. Having duplicate functions for task_join and task_completed just for discarpet seems dumb.
This could be solved by using mixins into carpet but thats also not a clean solution.

**Comment by GunnyWaffle** [comment]
It's a shame that this can't be cleanly introduced as a native scarpet `task`. Duplicating the `task_*` family of functions for Discarpet feels like a sloppy pseudo-branch too. Not ideal and may lead to confusion.

I assume that the only alternative left is to provide a callback? No `task` based functionality. Or is that not possible as well?
Worst case scenario, `dc_user_from_id` could block and require a thread, throwing if used on the main thread. That way developers are at least informed.

**Comment by replaceitem** [comment]
I might make a PR to fabric-carpet to make the TaskValue more extendable, should be simple enough.

**Comment by replaceitem** [comment]
Now I'm rethinking this again, maybe it would be better to just directly return the value, and have them be blocking, and leaving the threading to scarpet.

### Using scarpet tasks

So as an example, multiple chained api calls:
```
// blocking version
user = dc_user_from_id(id);
channel = user~'private_channel';
message = dc_send_message(channel,'Hey!');
dc_react(message,'👍');
```
Conclusion: intuitive, but blocking

```
// async version
task(_()-> (
  user = dc_user_from_id(id);
  channel = user~'private_channel';
  message = dc_send_message(channel,'Hey!');
  dc_react(message,'👍');
);
```
Conclusion: also intuitive, but not blocking


### returning a task

So as an example, multiple chained api calls:
```
// blocking version
user = task_join(dc_user_from_id(id));
channel = task_join(user~'private_channel');
message = task_join(dc_send_message(channel,'Hey!'));
task_join(dc_react(message,'👍'));
```
Conclusion: ugly

```
// async version
task_then(dc_user_from_id(id), _(user) -> (
  task_then(user~'private_channel', _(channel) -> (
    task_then(dc_send_message(channel,'Hey!'), _(message) -> (
      dc_react(message,'👍');
    );
  );
);
```
Conclusion: ugly


So i think this is much better than returning a value, so my idea was bad after all and i was overthinking things...

**Comment by GunnyWaffle** [comment]
That's a good use case exercise. If all API calls were wrapped in tasks, then that does very quickly become messy. If it were only `dc_user_from_id` it wouldn't be too bad. But all calls? That becomes a task sandwich.

At that point, it would be better to clearly document which functions block and which do not.

**Comment by replaceitem** [comment]
Yeah, blocking functions would have to be marked of course. The example i gave is obviously an extreme case, with many consecutive blocking calls, but `dc_user_from_id` won't be the only case of blocking functions. For example, in `dc_send_message(channel,content,callback?)` the callback would be removed, and instead block and return the message as well.
But that's fine i think.
```
dc_send_message(channel,'Hello',_(message)->(
  ...
);
```
is just as readable as
```
task(_()->(
  message = dc_send_message(channel,'Hello');
  ...
);
```

**Comment by GunnyWaffle** [comment]
I've folded in the additions introduced by release 1.1.0 and they work flawlessly.
Though `dc_get_user_color` returning null if no color is present was a surprise. That should either be documented or changed to be the Discord default role color hex.

Thank you so much for the work done here. Truly brought a lot of opportunities to my server!

**Comment by replaceitem** [comment]
Yeah should document that
https://github.com/replaceitem/carpet-discarpet/commit/59d25265e2f4851c8c85a3ac495dd45fcf5db2a6
