### ISSUE TITLE
discarpet 1.2.0 failed post 1.17.1

### ISSUE THREAD

**Issue by chezrlz** [replaceitem/carpet-discarpet#24]
(removed file)
server wouldn't launch with discarpet 1.2.0 installed. Once removed, it worked perfectly.

**Comment by replaceitem** [comment]
The log you attached seems like the wrong one? It doesn't contain a crash.
Do you by any chance have a crash report or log from with discarpet installed?

**Comment by replaceitem** [comment]
Make sure you have carpet version 1.4.57 or above, since versions below arent compatible

**Comment by chezrlz** [comment]
Oh my bad, I am sorry about that. I don't have any crash reports as it never crashed just failed to start, but here is the actual log I wanted to send. Yes I have carpet 1.4.57 installed. Is there any other information I could supply that might be useful?
[2022-03-06-3.log.gz](https://github.com/replaceitem/carpet-discarpet/files/8209835/2022-03-06-3.log.gz)

**Comment by replaceitem** [comment]
The problem is likely that you are using java 16, where the mod's mixins use compatibility with java 17 since it's mainly 1.18, so using java 17 should work.

**Comment by chezrlz** [comment]
Oh crap I didnt even notice. I assumed ninite would update to java 17 but apparently not. Ill try that and close this issue if it works.

**Comment by chezrlz** [comment]
Java 17 resolved the issue
