### ISSUE TITLE
dc_send_webhook allows mentions, where http POST can disable

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#25]
Titling this one was difficult.
Below is a screenshot of a few tests I ran, stumbling upon a possible oversight or limitation.
![image](https://user-images.githubusercontent.com/2184320/157788741-ebe0df6a-9c52-49bf-991d-183d9dabb5f4.png)
When using the following code with http POST, I specify that no @ mentions are to be parsed, disabling @ here/everyone/role/name mentions to avoid user abuse when linking Minecraft chat to Discord chat.
```
_webhook(player, message) -> (
	body = {
		'content' -> message,
		'embeds' -> null,
		'allowed_mentions' -> { 'parse' -> [] },
	};
	
	if (player != null,
		body:'username' = player;
		body:'avatar_url' = str(global_avatar_api, player~'uuid');
	);
	
	task(_(b)->http('POST', global_webhook, 10000, 10000, b), encode_json(body));
);
```
I adjusted the code to use the new `dc_send_webhook` function introduced in v1.2.1.
```
_webhook(player, message) -> (
	body = {
		'content' -> message,
		'embeds' -> null,
		'allowed_mentions' -> { 'parse' -> [] },
	};
	
	profile = {};
	
	if (player != null,
		profile:'name' = player;
		profile:'avatar' = str(global_avatar_api, player~'uuid');
	);

	task(_(b, p)->dc_send_webhook(global_webhook, b, p), encode_json(body), profile);
);
```
The first three messages show the initial problem.
1) Minecraft player saying `"test"` (avatar image cache not populated)
2) Discord user saying `"ah"`
3) Minecraft server running `"say test"` (default bot avatar)
The profile works as advertised, but the content is treated as a raw string message. I suppose I should have realized that to begin with though, as that is the documented usage. I adjusted the code to send the message directly.
```
_webhook(player, message) -> (	
	profile = {};
	
	if (player != null,
		profile:'name' = player;
		profile:'avatar' = str(global_avatar_api, player~'uuid');
	);

	task(_(msg, p)->dc_send_webhook(global_webhook, msg, p), message, profile);
);
```
As expected, this allows users to @ mention anything. As seen in the subsequent messages. The last message is using the original webhook code that disables @ mentions, to demonstrate it.

Let me know if you need more info!

**Comment by replaceitem** [comment]
Added in 80f1bd52fd25f883dd746766c3cf69a68eb20b8b
https://github.com/replaceitem/carpet-discarpet/releases/tag/v1.2.2
