### ISSUE TITLE
[Security] Bot token can potentially be leaked to clients in current implementation

### ISSUE THREAD

**Issue by altrisi** [replaceitem/carpet-discarpet#3]
In base Carpet, rules are by default shared with clients: when they connect, when one changes, etc. There is a protocol for that, and it's thought for rules that have better integration or an effect in the client-side too, so clients can react accordingly (fogOff, shulkers stacking in inventories, etc).

Luckily, synchronization of custom extension's SettingsManager rules is currently broken (tracked at gnembon/fabric-carpet#546, incorrectly closed), and wont send rules from extension's custom managers _when clients are connecting to the server_. However **those are still sent when the rule changes with players online**, although they aren't recognized by Carpet in the client. Someone with a modified client could, therefore, listen to the rule change and save it somewhere to abuse it.

_at [ServerNetworkHandler.java#L145](https://github.com/gnembon/fabric-carpet/blob/8e3c330e04ce66abae13057281bc7447836be37a/src/main/java/carpet/network/ServerNetworkHandler.java#L145-L155)_
```java
    public static void updateRuleWithConnectedClients(ParsedRule<?> rule)
    {
        for (ServerPlayerEntity player : remoteCarpetPlayers.keySet())
        {
            player.networkHandler.sendPacket(new CustomPayloadS2CPacket(
                    CarpetClient.CARPET_CHANNEL,
                    DataBuilder.create().withRule(rule).build()
            ));
        }
    }
```
_one line hasn't been included in this snippet due to secrecy_

I'm currently fixing gnembon/fabric-carpet#546, so I wanted to let you know about this. Don't worry, I'll probably also make a PR here before sending the PR with the fix to base Carpet.

**Comment by replaceitem** [comment]
Thanks for pointing that out and making the PR!
I'll look into it tomorrow

And thanks for removing that line, i just scrolled over it today and saw it ;)
