### ISSUE TITLE
Unable to use slash commands in v1.3.0 and v1.3.1

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#30]
This one is hard to diagnose, since the replacement for `dc_delete_slash_command` is not fully documented. I took a guess with the following: (as per release notes for v1.3.0)
```
for (global_server~'slash_commands',
	dc_delete(_);
);
```
This appears to work as expected. Slash commands are removed immediately if not recreated.
Then matched the documented example for creating a slash command:
```
dc_create_slash_command({
	'name' -> 'test',
	'description' -> 'This is a test'
}, global_server);
```
With no errors in the server console, I get the following in Discord:
![image](https://user-images.githubusercontent.com/2184320/166505946-c0549cee-b8ce-40ad-98ab-3e381e39afea.png)
I've tried restarting my MC server and reloading the script. I am unable to get any slash commands to work, but they do register and are viewed successfully in my Discord client.

**Comment by replaceitem** [comment]
That's odd, they work for me. I've updated the [Slash command example](https://github.com/replaceitem/carpet-discarpet/blob/master/docs/Examples.md#slash-commands) to an updated script that works. Can you try it with that one?
(Make sure to specify a valid server, since `dc_server_from_id` could otherwise return null, which would register the commands globally, which take a while.)

**Comment by GunnyWaffle** [comment]
I tried your example and it still fails.
I've confirmed that my `global_server` is not null as I can iterate `slash_commands` in `__on_start` and see all slash command names.
Worth noting that in v1.3.1 sometimes Discord reports `The application did not respond` instead of being invalid.

Oh, I actually see a new error in v1.3.1!
```
[13:51:43] [pool-11-thread-1/INFO]: Thread failed
:    ,
      task(_() -> ( HERE>> dc_respond_interaction(command, 'RESPOND_IMMEDIATELY', 'test.')));
   );
Incorrect argument passsed to 'dc_respond_interaction' function.
Usage: 'dc_respond_interaction(interaction, string, values...)' in discord at line 249, pos 19
```
From this code: (slimmed down and reproduces the same)
```
__on_discord_slash_command(command) -> (
	task(_() -> (dc_respond_interaction(command, 'RESPOND_IMMEDIATELY', 'test.')));
);
```

**Comment by GunnyWaffle** [comment]
Wait, I think I had a merge conflict in my code and I sampled a bad task that did not encapsulate the interaction object correctly.
This code works fine. I'm looking to see if I have a merge conflict elsewhere.
```
__on_discord_slash_command(command) -> (
	task(_(c) -> (
		dc_respond_interaction(c, 'RESPOND_IMMEDIATELY', 'Contact Gunny, something went wrong.')
	)
	, command);
);
```

**Comment by GunnyWaffle** [comment]
I managed to fix my code. Looks like a few undocumented changes occurred, alongside a couple of merge conflicts on my own end, that broke my script. These were masked by the other issues I reported.

For the `Slash command interaction` value:
1. `'command':0` is not documented and was not working for me (I believe). I instead used the `'command_name'` property to fix my code.
2. While `'options'` is no longer documented, it still works. EX: `interaction~'options':'my_argument_name'`

And uh...I was about to verify that `'command'` no longer worked, just to make sure. And now my slash commands are invalid again? They were working, and now they no longer work.
Should I not be iterating over all slash commands and deleting them prior to making them in `__on_start`? Is that handled for me now?

EDIT: slash commands are working again without a change to my script. I confirmed that `'command'` is null for the `Slash command interaction` value

EDIT2: I waited for 10 minutes and the command worked again. No changes to code. I think something is amiss with rate limiting when recreating slash commands.

EDIT3: Actually, `'options'` is now null as well. This was a rather useful property as it allowed me to pick options by name. Now I have to scan through the `'arguments'` list to get the option I want? Am I understanding this correctly?
was
```
val = interaction~'options':'my_arg';
```
is now
```
val = null;
for (interaction~'arguments',
	if (_~'name' == 'my_arg', val = _~'value');
);
```
instead of
```
val = interaction~'arguments':'my_arg'~'value';
```

**Comment by replaceitem** [comment]
I added the old `options` back in 84ffdcfb18a41d41bd7b52070e5239744b90d15b (now `arguments_by_name`)
It returns a map with all options by their name

**Comment by GunnyWaffle** [comment]
For what it's worth, I've been testing the slash commands periodically without restarting the server nor reloading the script. They have been error-free for a long while now. I suspect that Discord is now throwing a fit in regards to recreating slash commands where it did not prior.

Either due to the new `dc_delete` for loop code that deletes them one by one through scarpet, or due to a change on Discord's end recently in regards to rate limiting.

I also came to realize something concerning. If I am to use the following code, when does the `slash_commands` list update?
```
for (global_server~'slash_commands',
	dc_delete(_);
);
```
Is this internally modifying that list with each call to `dc_delete` as I iterate? Or is this safe since I grab a copy of the list once before iterating over it? I wonder if this is at all related to the issues I was encountering.

Thank you for the `arguments_by_name` by the way. Much appreciated!

**Comment by replaceitem** [comment]
The method of deleting the slash commands before `dc_delete` was internally also just iterating and deleting them one by one.

There is a batch slash command updater, which i may implement at some point though.

The `for` loop only evaluates the list value once, so that shouldn't be a problem.

**Comment by replaceitem** [comment]
Is everything here resolved now?
In that case i will close this

**Comment by GunnyWaffle** [comment]
I believe so.
To summarize, this was a perfect storm of:
- missed changes to documentation
- merge conflicts on my end
- Discord suddenly having a disagreement with recently recreated slash commands

Really painted a skewed picture. Things seem resolved now. Just a slight inconvenience to wait 5-15min to use recreated slash commands again.

Thank you for the support and answering my questions!
