### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by cohenerickson** [replaceitem/carpet-discarpet#32]
When can we expect 1.19 support?

**Comment by replaceitem** [comment]
Have you tested if it works with 1.19?
It might even just work out of the box with the newest release, since it's not associated with mc 1.18.
If it doesn't, i will update it next week.

**Comment by GunnyWaffle** [comment]
I can confirm that the server won't even start due to a large amount of failed mixins. I suspect the chat overhaul in 1.19 affected this mod, but that is just a guess.

**Comment by replaceitem** [comment]
True, the chat changes broke things for sure. Will update in about a week

**Comment by replaceitem** [comment]
Updated in cab07248922fc3f677edfc729b50567a395b3f07
