### ISSUE TITLE
Missing system messages v1.4.0

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#33]
It looks like `__on_system_message` is receiving fewer message types than in v1.3.2. Both `/say` and `/me` no longer fire this event.

This might be another limitation imposed by 1.19, such as losing `entity` in `__on_system_message`. If so, that sucks.
I can get by without this, but it was great having both `/say` and `/me` in my chat bridge.

**Comment by replaceitem** [comment]
Good point, all the system message logging is a bit more all over the place now, so i would have to implement them seperately.
I guess i can bring the /say and /me back manually

**Comment by replaceitem** [comment]
Added in b8c87c782e3ac321bf0980c86f5a9666d1c616bd

**Comment by replaceitem** [comment]
Sadly the formatting is the same as a normal chat message, since that's the way they get logged as well (pretty sure it was different in 1.18, with proper `[name] msg` and `* name msg`. Now it's all `<name> msg`)

**Comment by GunnyWaffle** [comment]
That's odd. I tested this earlier in 1.19 and they appeared in chat as `[name] msg` and `* name msg`.

**Comment by replaceitem** [comment]
In chat they do, but in the console it's all `<name> msg`

**Comment by GunnyWaffle** [comment]
I did some digging. Looks like the console formatting is a [known bug](https://bugs.mojang.com/browse/MC-252539) that is fixed in [snapshot 22w24A](https://www.minecraft.net/en-us/article/minecraft-snapshot-22w24a).

**Comment by replaceitem** [comment]
Interesting, i will upload a release later like it is now,  and when 1.19.1 drops, i will fix the formatting in the event too
