### ISSUE TITLE
"allowed_mentions" properties are not set to false by default

### ISSUE THREAD

**Issue by CarbonGhost** [replaceitem/carpet-discarpet#37]
The `message_content` `allowed_mentions` property does not have it's value set to false by default, as mentioned on this wiki page:
https://replaceitem.github.io/carpet-discarpet/parsables/allowed-mentions

**Comment by replaceitem** [comment]
If the `allowed_mentions` are specified in the message content, all the options are false, meaning all mentions are disabled (See [here](https://github.com/replaceitem/carpet-discarpet/blob/master/src/main/java/Discarpet/script/parsable/parsables/AllowedMentionsParsable.java#L14-L16)).
What you are probably refering to is not specifying `allowed_mentions` at all (meaning it is not an entry in the message content map), in which case mentions are *not* disabled.

Hope this clears it up.

**Comment by CarbonGhost** [comment]
Reading back on it my issue was phrased poorly. What I was actually referring to was `message_content` defined only by a string, which obviously does not define the `allowed_mentions` properties, like this:

```js
dc_send_message(channel, 'This is just a string');
```

Your comment does clear that up, thanks!
