### ISSUE TITLE
bug(?): discarpet does not seem to work when `__on_close()`

### ISSUE THREAD

**Issue by macimas** [replaceitem/carpet-discarpet#44]
```py
__on_start() -> dc_send_message(…, 'bridge is established!'); // it works!
__on_close() -> dc_send_message(…, 'bridge is killed.'); // doesn't work
```
it's a minor issue, but i'm curious why this doesn't work?

**Comment by replaceitem** [comment]
When i tried this it worked.
I tried both unloading the script (which sent the message) and stopping the server (with /stop).
What did you do to test that?

**Comment by macimas** [comment]
...that's weird, now it works
i'll close this issue for now i guess?

**Comment by replaceitem** [comment]
Alright, if you can reproduce it again, just reopen it.
