### ISSUE TITLE
Missing Full Documentation Full.md

### ISSUE THREAD

**Issue by Isax03** [replaceitem/carpet-discarpet#6]
It would be really helpful, if you added a Full Documentation page

**Comment by replaceitem** [comment]
Added with 96bdd0bb207d2ad7242adbf4b438a6a48816e209

**Comment by joex92** [comment]
I can't find in the docs where the script files are saved 🤔

**Comment by replaceitem** [comment]
For reference on how scarpet scripts work, see the scarpet docs here: https://github.com/gnembon/fabric-carpet/blob/master/docs/scarpet/Full.md#app-structure
(Link points to section on how apps work, and where they are saved)
